# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_records_app', '0005_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='debit_or_deposit',
            field=models.CharField(choices=[('+', 'deposit'), ('-', 'withdraw')], max_length=1),
        ),
    ]
