# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_records_app', '0006_auto_20161028_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_or_deposit',
            field=models.CharField(choices=[('+', 'Deposit'), ('-', 'Withdraw')], max_length=1),
        ),
    ]
