# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_records_app', '0007_auto_20161028_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
